{
 "title": "NGINX  Host Path 详细",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "tags": [ "nginx" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count, host)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count{host=~\"$host\"}, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds_sum:err_rate_by_host_path{host=~\"$host\", path=~\"$path\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "QPS by Path",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\", path=~\"$path\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "$path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "fullurl" },
  {
   "title": "4XX Count（5 min）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\" ,status=~\"3..\"}[5m])) by (instance)",
     "legendFormat": "3XX - {{instance}}"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\", status=~\"40[^3]{1}|4[^0]{1}.\"}[5m])) by (instance)",
     "legendFormat": "4XX(with out 401 & 403) - {{instance}}"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\" , status=~\"5..\"}[5m])) by (instance)",
     "legendFormat": "5XX - {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p999_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:avg_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "2XX QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_path_2XX{host=~\"$host\", path=~\"$path\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "2XX P90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p999_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\", path=~\"$path\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P90 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p90"
    }
   ]
  },
  {
   "title": "P99 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p99"
    }
   ]
  },
  {
   "title": "P999 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p999"
    }
   ]
  }
 ]
}