{
 "title": "NGINX  Host",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by(host) ",
     "legendFormat": "4XX - 1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m])) by(host) ",
     "legendFormat": "5XX - 1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m])) by(host) ",
     "legendFormat": "3XX - 1min"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (job:nginx_request_duration_seconds:qps_by_instance_host_2XX{host=~\"$host\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds_sum:err_rate_by_host_path{host=~\"$host\"} > 0.01",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_2XX{host=~\"$host\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_4XX{host=~\"$host\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_5XX{host=~\"$host\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "4XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_4XX{host=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX Latency(延时)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p999_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-P999"
    },
    {
     "expr": "job:nginx_request_duration_seconds:p99_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-P99"
    },
    {
     "expr": "job:nginx_request_duration_seconds:avg_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-avg"
    }
   ]
  },
  {
   "title": "5XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_5XX{host=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TOP 10 QPS",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "TOP 10 4XX over 10min",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (path)(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[10m]))>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX over 10min",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (path)(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[10m]))>0)"
    }
   ]
  }
 ]
}